### ISSUE TITLE
Feature Request: Sticky Headers

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [dorkyboi/react-native-calendar-timetable#11]
Would be nice to make the header sticky, so that during the scrolling a user can see which date he picked. Otherwise great job!!!

**Comment by dorkyboi** [comment]
We could add one, but then with default styles it would look like [this](https://imgur.com/a/jNIxIsd). As you can see, when using React Native's Animated API, they move with a significant delay. This could be resolved with the help of react-native-gesture-handler and react-native-reanimated, but libraries are simply too big to consider adding them. If only there were a way to check if these libraries are already present in the project… 🤔 
I will add this feature in v2 if this performance is sufficient for you.

**Comment by NilsBaumgartner1994** [comment]
I Made a workaround currently. I added an absolute view and gave the timeContainer an opacity
