### ISSUE TITLE
Feature Request: Render Function for Time on left

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [dorkyboi/react-native-calendar-timetable#13]
Would be nice to customize the rendering of the time components on the left.

**Comment by NilsBaumgartner1994** [comment]
Just like for the header.

**Comment by dorkyboi** [comment]
This should be easy to implement. Will add in v2.

**Comment by dorkyboi** [comment]
Version 1.0.2 should have the feature you were looking for 👌🏼
