### ISSUE TITLE
Feature Request: Start Scrollview at position

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [dorkyboi/react-native-calendar-timetable#14]
Would be nice to let the scrollview start at some specific time or at the current time.

**Comment by dorkyboi** [comment]
This feature is probably not implementable because there is no vertical scroll in the component. It relies on developer to wrap it in one during usage. Vertical scrollview is omited to prevent issues with nesting scrollviews.

**Comment by NilsBaumgartner1994** [comment]
What abou horizontal start?
For example i want to start at the current day of the week but the table should always begin with Monday, which may be too large for the screen, but I want to be able to scroll to the left?
