### ISSUE TITLE
Calendar time issue

### ISSUE THREAD

**Issue by zenesys0081** [dorkyboi/react-native-calendar-timetable#20]
1. On the calendar after 11am it shows 12 am. Should be 12pm.

**Comment by dorkyboi** [comment]
It was fixed in your previous issue.
![изображение](https://user-images.githubusercontent.com/23461412/216931904-dcfcced2-96c5-4343-b726-d0003483c624.png)
Make sure you are using v1.0.4+

**Comment by dorkyboi** [comment]
Validated that it is working in v1.0.6

**Comment by zenesys0081** [comment]
Thanks for updating.

From: Dmytro Kardava ***@***.***>
Date: Monday, 6 February 2023 at 14:52
To: dorkyboi/react-native-calendar-timetable ***@***.***>
Cc: Pravesh Kumar ***@***.***>, Author ***@***.***>
Subject: Re: [dorkyboi/react-native-calendar-timetable] Calendar time issue (Issue #20)

Closed #20<https://github.com/dorkyboi/react-native-calendar-timetable/issues/20> as completed.
