### ISSUE TITLE
Unable to change the time format (24 hour format to 12 hour format) and time interval in UI

### ISSUE THREAD

**Issue by DeepikaSharma5** [dorkyboi/react-native-calendar-timetable#6]
@GeorgeHop @dorkyboi  Is there a possible way to display the time as 8:00 AM | 8:00 PM (as 12 hour format) 

And can we show the time interval as 30 minutes. I mean the default time interval is 1 hour. 08:00, 09:00, 10:00 ..... But can I show the time as 08:30, 09:00, 09:30, 10:00 .....

It is better to have these options.

**Comment by dorkyboi** [comment]
Hi @DeepikaSharma5 
At the moment there is no such functionality.
We can implement an optional 12h mode, you can expect it in a next version.
Time interval feature, however, would take a lot of time to implement, time that we do not have currently. If you would really like this feature to be present - you are always welcome to submit a PR.

**Comment by dorkyboi** [comment]
Added `is12Hour` prop in v0.4.7
